"""Load the settings file: global config plus the accounts to sync.

Everything lives in one JSON file (``AUTOSAVER_SETTINGS_FILE``, default
``settings.json``): top-level keys are global settings, and ``users`` is the
list of accounts. Each account needs a ``refresh_token`` (generated by the PKCE
web app) and may override any of the playlist settings. See
``settings.example.json``.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass

from .config import (
    DEFAULT_PLAYLIST_DESCRIPTION,
    DEFAULT_PLAYLIST_NAME,
    DEFAULT_TRACK_COUNT,
    Config,
    ConfigError,
)

DEFAULT_SETTINGS_FILE = "settings.json"


def settings_path() -> str:
    """Path to the settings file (``AUTOSAVER_SETTINGS_FILE`` or the default)."""

    return os.getenv("AUTOSAVER_SETTINGS_FILE", DEFAULT_SETTINGS_FILE).strip() or (
        DEFAULT_SETTINGS_FILE
    )


@dataclass
class UserConfig:
    """One account to sync, with defaults-applied playlist settings.

    Attribute names mirror :class:`~spotify_autosaver.config.Config` so the sync
    functions accept either object.
    """

    name: str
    refresh_token: str
    track_count: int
    playlist_id: str | None
    playlist_name: str
    playlist_public: bool
    playlist_description: str


def _user_from_entry(entry: dict, index: int) -> UserConfig:
    where = f"users[{index}]"
    if not isinstance(entry, dict):
        raise ConfigError(f"{where} must be a JSON object")

    token = str(entry.get("refresh_token") or "").strip()
    if not token:
        raise ConfigError(f"{where} is missing a non-empty 'refresh_token'")

    try:
        track_count = int(entry.get("track_count", DEFAULT_TRACK_COUNT))
    except (TypeError, ValueError) as exc:
        raise ConfigError(f"{where} has an invalid 'track_count'") from exc
    if track_count < 1:
        raise ConfigError(f"{where} 'track_count' must be a positive integer")

    return UserConfig(
        name=str(entry.get("name") or f"user{index + 1}"),
        refresh_token=token,
        track_count=track_count,
        playlist_id=(entry.get("playlist_id") or None),
        playlist_name=str(entry.get("playlist_name") or DEFAULT_PLAYLIST_NAME),
        playlist_public=bool(entry.get("playlist_public", False)),
        playlist_description=str(
            entry.get("playlist_description") or DEFAULT_PLAYLIST_DESCRIPTION
        ),
    )


def load_settings(path: str | None = None) -> tuple[Config, list[UserConfig]]:
    """Load global config and the accounts to sync from the settings file."""

    path = path or settings_path()
    if not os.path.exists(path):
        raise ConfigError(
            f"Settings file {path!r} not found. Copy settings.example.json to "
            f"{path} and fill it in (generate tokens with the PKCE web app)."
        )

    try:
        with open(path, encoding="utf-8") as handle:
            data = json.load(handle)
    except json.JSONDecodeError as exc:
        raise ConfigError(f"{path} is not valid JSON: {exc}") from exc

    if not isinstance(data, dict):
        raise ConfigError(f"{path} must be a JSON object with 'client_id' and 'users'.")

    config = Config.from_dict(data)

    entries = data.get("users") or []
    if not entries:
        raise ConfigError(f"{path} has no accounts — add at least one to 'users'.")

    users = [_user_from_entry(entry, i) for i, entry in enumerate(entries)]
    return config, users
